# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-27 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0003_auto_20200127_1746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStats',
            new_name='Statistic',
        ),
    ]
